### PR TITLE
Improve 3D model performance

### PR DESCRIPTION
**Pull request by TIMMLOPK**
It will be faster

### CODE REVIEW

**Comment by craftzdog** [comment]
Is this necessary? Because the voxel dog is simple enough to render on mobile devices.

**Comment by TIMMLOPK** [comment]
It is optional setting but it maybe improve loading time of High-performance devices

**Comment by craftzdog** [comment]
I guess it doesn't improve loading time but rendering performance.
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2

**Comment by TIMMLOPK** [comment]
Yes, you are right .I guess adopting Draco to load model should be suitable way.It maybe better than this. I will change the pull request later.

**Pull request closed without merging**
